### ISSUE TITLE
`#warning` breaks MSVC builds including cl2.hpp

### ISSUE THREAD

**Issue by MathiasMagnus** [KhronosGroup/OpenCL-CLHPP#121]
When using MSVC one gets the following error when trying to include cl2.hpp:
```
fatal error C1021: invalid preprocessor command 'warning'
```
Note that there is a solution on [SO](https://stackoverflow.com/a/279669).

**Comment by bashbaug** [comment]
The obvious alternative is to switch to `#pragma message`, which is what we do in other places like the OpenCL headers:

https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_version.h#L22

This isn't quite the same, since a warning will fail the build when warnings as errors are enabled whereas a message will not, but it's pretty close.

Do we want to switch to `#pragma message`?  If so, this is an easy fix.

**Comment by jrprice** [comment]
> Do we want to switch to #pragma message?

Makes sense to me.

**Comment by MathiasMagnus** [comment]
I too vote for pragma message.
