### ISSUE TITLE
default_initialized_ declared weak after being used

### ISSUE THREAD

**Issue by nerdralph** [KhronosGroup/OpenCL-CLHPP#17]
Got a few of these errors with gcc -fsanitize=undefined.
Removing "**attribute**((weak))" gets it to compile.

**Comment by keryell** [comment]
The issue here is that it is not possible to initialize a global variable only once when it is done inside the cl.hpp headers which are included in different compilation units.
So this is a way to achieve this with GCC and Clang, waiting for inline variable in C++17 and I am afraid we have to rely on these extensions in the meanwhile...
The proposal which was adopted in Oulu last June for C++17:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0386r2.pdf

**Comment by mz24cn** [comment]
weak (CL_HPP_DEFINE_STATIC_MEMBER_) also troubles me: https://www.khronos.org/bugzilla/show_bug.cgi?id=1937 or #4 
So we should wait for C++17? @keryell @jrprice

**Comment by keryell** [comment]
@mz24cn if the weak attribute is the problem, you can always use less portable things while waiting for C++17, like in https://github.com/triSYCL/triSYCL/blob/master/include/CL/sycl/detail/global_config.hpp#L59

**Comment by mz24cn** [comment]
It seems SYCL is interesting and more high-level than cl2.hpp. 
Do I need not write opencl device-side C program if I switched to SYCL? 
Will SYCL compiler automatically generate opencl device code? 
Does SYCL introduce overhead for the convenience, compared with manually enqueue kernel tasks? 
What is relationship on SYCL 2.2 with OpenCL C++ 2.2?
thank you, @keryell , I will spend time to be familar with SYCL.

**Comment by keryell** [comment]
@mz24cn OpenCL and SYCL are both from Khronos but, as you said, they are not at the same level.
OpenCL C++ 2.2 and SYCL 2.2 assume both the same hardware capabilities.
But OpenCL C++ is a language to write kernels, with the host part using for example `CL/cl2.hpp` from this repository to do the house-keeping, while SYCL is a single-source framework to express both the host code *and* the kernel part in a pure C++ way without any extensions.
So you do not need to write separate kernels with SYCL. The compiler will generate them for you. Today only ComputeCpp implementation is mature enough to achieve this.

To add a little bit of confusion :-) , SYCL comes also with an interesting OpenCL interoperability mode that allows you to call OpenCL C/C++/SPIR/... kernels from SYCL, while keeping the concept of accessors to alleviate you from managing the buffer transfers explicitly.
You can find in the README of https://github.com/triSYCL/triSYCL some links to some presentations introducing the various concepts and differences.

**Comment by mz24cn** [comment]
thanks for your explanantions, @keryell It seems you are not confident with your own triSYCL since you said "Today only ComputeCpp implementation is mature enough to achieve this" :-) But I still like open source implemention. where is the gap between triSYCL and ComputeCpp currently?

Considering the complexity of device-side OpenCL code, I don't expect the SYCL compiler is so smart to generate optimized device-side code. I only need it allows me to use high-level C++ features such as templates, and other repeated code such as memory transfer. Do you think triSYCL is mature enough to do such transformations without introducing perceptible overhead?

**Comment by keryell** [comment]
@mz24cn It is not about confidence, it is just about facts. :-)
Why are you not using the free community edition of ComputeCpp that provides you single-source C++?
triSYCL is not mature enough to have a low-overhead abstraction on top of OpenCL but this is the goal of SYCL at large.
But this discussion in off-topic here. Perhaps you can ask question on https://forums.khronos.org/showthread.php/13046-Official-SYCL-2-2-Provisional-feedback-thread for example.

**Comment by nigelgbanks** [comment]
Is there any intention to update this now that C++17 has been standardized?

**Comment by keryell** [comment]
@nigelgbanks good idea. Feel free to send a PR.

**Comment by jrprice** [comment]
Adopting this C++17 feature would bump our minimum compiler versions to things like GCC 7, Visual Studio 2017 and Intel 2019 (as yet unreleased), which might cause problems for several users today.

**Comment by jeffhammond** [comment]
Intel 19 has been released.  https://software.intel.com/en-us/articles/intel-c-compiler-190-for-linux-release-notes-for-intel-parallel-studio-xe-2019 shows April but that was probably the beta release date - according to https://registrationcenter.intel.com/en/products/, the gold version was released in September.

**Comment by keryell** [comment]
@jrprice no, you can just test if the compiler is at least C++17 with a feature macro such as `__cplusplus`, otherwise use the default ugliness... Of course it is not a great achievement compared to what we have today... :-)

**Comment by nigelgbanks** [comment]
I've sent up a pull https://github.com/KhronosGroup/OpenCL-CLHPP/pull/52 which resolves my local compilation issues, I'll encorporate any relevant feedback you may have.

**Comment by jrprice** [comment]
The above C++17-based fix has now been merged (a807dcf). This is probably the best we can do for now so I'll close this issue. If anyone disagrees please reopen.

**Comment by TSlivede** [comment]
@jrprice If I'm not mistaken, this issue is only solved for `cl.hpp` even though the same problem exists for `cl2.hpp`. I've submitted a PR (https://github.com/KhronosGroup/OpenCL-CLHPP/pull/83) that fixes this for `cl2.hpp`.
