### ISSUE TITLE
Merge changes from master into opencl21 branch

### ISSUE THREAD

**Issue by pavanky** [KhronosGroup/OpenCL-CLHPP#26]
There have been a lot of fixes in master that deal with compilation errors. These have not been merged into opencl21 branch yet. 

Would it be possible to perform a merge from master into opencl21?

**Comment by jrprice** [comment]
Done.

Now that there is at least one OpenCL 2.1 implementation publicly available, I hope to test out the new features in this branch so that we can finally merge this into master. If you're trying out this version of the header on a 2.1 platform, I'd appreciate some feedback on how well it is working to speed this process up.
