### ISSUE TITLE
SubBuffers & RefCounts of cl_mem

### ISSUE THREAD

**Issue by tobwes** [KhronosGroup/OpenCL-CLHPP#32]
Good evening,

I think that I've found a bug in your cl.hpp files (possibly cl2.hpp as well, I haven't checked.)

The issue is that when creating a SubBuffer of an ordinary Buffer, you call clCreateSubBuffer and store the resulting cl_mem in a Buffer object. When this Buffer goes out of scope, it calls clReleaseMemObject on its wrapped cl_men object. Since you didn't retain the cl_mem object when you created the SubBuffer, this means that the ref count of the cl_mem is one too low.

Consider this:
```
cl::Buffer buf = cl::Buffer(context,CL_MEM_READ_WRITE,sizeof(int)*100);
cl::Buffer subbuf = buf.createSubBuffer(CL_MEM_READ_WRITE,CL_BUFFER_CREATE_TYPE_REGION, &region); // region needs to exists
/* as soon as subbuf goes out of scope this invalidates buf! */
```
Solution: call buffer.retain() in createSubBuffer wrapper.

Remark: I don't even know if you're supposed to retain/release sub buffer objects in opencl. I couldn't find any specification about this as well.

**Comment by jrprice** [comment]
I'm not sure I understand the problem. When a `cl::Buffer` object corresponding to a sub buffer  is destroyed, we call `clReleaseMemObject` on the sub buffer `cl_mem`, /not/ the parent buffer. In your example, when `subbuf` goes out of scope, the sub buffer that it wraps will be destroyed, but the parent buffer `buf` will still be valid.

Are you experiencing a problem with these APIs?

**Comment by tobwes** [comment]
The OpenCL documentation is not clear on that point, whether a subbuffer needs to be released. (Intuitively, I'd say there's no sense in releasing a subbuffer, because it owns no dedicated memory.)

Anyway, attached is an example that lets the subbuffer go out of scope before the kernel is running and then crashes with a segmentation fault (on both platforms, Clover and pocl). If I prevent the subbuffers from going out of scope (e.g. declare them static in lines 20ff., thus the destructor is not called and the memory is not released), the program runs just fine.



[main.txt](https://github.com/KhronosGroup/OpenCL-CLHPP/files/1382916/main.txt)
(hint: I had to use .txt, because GitHub didn't let me upload a .cpp file.)

**Comment by jrprice** [comment]
I admit that It might not be crystal clear from the specification that sub-buffers should be released, but I'm afraid that is indeed the case. For example, if you look at the official OpenCL conformance tests, you can see that they call `clReleaseMemObject` on sub buffer objects when they are finished with them. An example of that is [here](https://github.com/KhronosGroup/OpenCL-CTS/blob/2821bf132378a9222ffb5830d08a6de6be67c699/test_conformance/api/test_mem_object_info.cpp#L354), and you can see that the parent buffer is also released a few lines later.

> Intuitively, I'd say there's no sense in releasing a subbuffer, because it owns no dedicated memory.

I understand where you're coming from, but I'd think about this slightly differently. When you release a sub buffer, you're not asking the runtime to deallocate the buffer memory, you're just saying that you are done with the sub buffer *object*. The sub buffer object is what contains information about where the sub buffer starts and ends, what the parent buffer is, etc. Releasing this object allows the runtime to free the memory used to hold this information - but it won't deallocate the memory used for the contents of buffer until you also release the parent buffer.

The OpenCL specification says this regarding `clReleaseMemObject`:

> If `memobj` is a buffer object, `memobj` cannot be deleted until all sub-buffer objects associated with `memobj` are deleted.

How does the runtime know when the sub buffer objects have been deleted? Because the user has called `clReleaseMemObject` on them!

I hope this helps clarify things. I would certainly expect your example code to fail for the above reasons - you're destroying the sub buffer before it's used.

**Comment by jrprice** [comment]
Closing this as it was not deemed to be an issue with the headers.
