### ISSUE TITLE
How to get CL_KERNEL_GLOBAL_WORK_SIZE values?

### ISSUE THREAD

**Issue by LeMoussel** [KhronosGroup/OpenCL-CLHPP#43]
I want to query the maximum global size that can be used to execute a kernel.
I do this
` cl::array<size_t, 3> kernel_global_work_size = my_kernel.getWorkGroupInfo<CL_KERNEL_GLOBAL_WORK_SIZE>(my_device);`

But I got error 
```
cl2.hpp:5771:12: note: candidate: template<class T> cl_int cl::Kernel::getWorkGroupInfo(const cl::Device&, cl_kernel_work_group_info, T*) const
     cl_int getWorkGroupInfo(
            ^~~~~~~~~~~~~~~~
cl2.hpp:5771:12: note:   template argument deduction/substitution failed:
cl2.hpp:5782:9: note: candidate: template<int name> typename cl::detail::param_traits<cl::detail::cl_kernel_work_group_info, name>::param_type cl::Kernel::getWorkGroupInfo(const cl::Device&, cl_int*) const
         getWorkGroupInfo(const Device& device, cl_int* err = NULL) const
```

How can I get `size_t[3]` values ?

**Comment by LeMoussel** [comment]
what do you think if in [cl2.hpp](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/input_cl2.hpp#L1218) I change

>  F(cl_kernel_work_group_info, CL_KERNEL_WORK_GROUP_SIZE, size_type) \

by

> F(cl_kernel_work_group_info, CL_KERNEL_WORK_GROUP_SIZE, cl::detail::size_t_array) \

and call like this :
`cl::array<size_t, 3> kernel_global_work_size = my_kernel.getWorkGroupInfo<CL_KERNEL_WORK_GROUP_SIZE>(my_device);`

**Comment by LeMoussel** [comment]
In [cl2.hpp](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/input_cl2.hpp#L1218), I add this :
`    F(cl_kernel_work_group_info, CL_KERNEL_GLOBAL_WORK_SIZE, cl::detail::size_t_array) \`
an do this
`cl::array<size_t, 3> kernel_global_work_size = my_kernel.getWorkGroupInfo<CL_KERNEL_GLOBAL_WORK_SIZE>(my_evice);`

No compilation error but OpenCL error -30 (Invalid Value)

**Comment by noma** [comment]
Ok, so the workaround, using the other variant call (with `cl::array` of course...) basically works, and the header can be easily fixed.

Now with the Invalid value we are back at the specification, which is not a bug, but requires carefully reading the specification. I though this was the original problem, as you initially didn't post any compilation errors.

Please carefully read the second part of my stack overflow answer, I guess you are using a normal kernel on normal device, and where the specification basically tells you, that `CL_INVALID_VALUE` will be what you get from that call. That's why I quoted the specification there.

**Comment by LeMoussel** [comment]
Yep I use a normal kernel on normal device and as indicated then it is normal to have `CL_INVALID_VALUE` 

> If device is not a custom device or kernel is not a built-in kernel, clGetKernelArgInfo returns the error CL_INVALID_VALUE.
